version: '3.8'
services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-jobcrawlerdb_user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-changeme}
      POSTGRES_DB: ${POSTGRES_DB:-jobcrawlerdb}
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - '5432:5432'

  python-api:
    build: ./python-api
    depends_on:
      - postgres
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER:-jobcrawlerdb_user}:${POSTGRES_PASSWORD:-changeme}@postgres:5432/${POSTGRES_DB:-jobcrawlerdb}
    ports:
      - '8000:8000'
    volumes:
      - ./python-api:/app  # For dev hot-reload

volumes:
  pgdata: