SKILL_ALIASES: dict[str, list[str]] = {
    "javascript": ["javascript", "js", "ecmascript"],
    "typescript": ["typescript", "ts"],
    "python": ["python", "py"],
    "java": ["java", "spring", "spring boot"],
    "c": [" c ", "c language"],
    "cpp": ["c++", "cpp"],
    "csharp": ["c#", "c sharp", ".net"],
    "go": ["golang", " go "],
    "rust": ["rust"],
    "react": ["react", "react.js", "reactjs"],
    "next.js": ["next.js", "nextjs", "next js"],
    "node.js": ["node.js", "nodejs", "node js"],
    "express": ["express", "express.js"],
    "nestjs": ["nestjs", "nest js", "nest.js"],
    "html": ["html", "html5"],
    "css": ["css", "css3"],
    "tailwind": ["tailwind", "tailwindcss"],
    "redux": ["redux"],
    "zustand": ["zustand"],
    "mongodb": ["mongodb", "mongo"],
    "postgresql": ["postgresql", "postgres", "psql"],
    "mysql": ["mysql"],
    "redis": ["redis"],
    "supabase": ["supabase"],
    "firebase": ["firebase"],
    "docker": ["docker", "containerization"],
    "kubernetes": ["kubernetes", "k8s"],
    "aws": ["aws", "amazon web services"],
    "azure": ["azure"],
    "gcp": ["gcp", "google cloud"],
    "git": ["git", "github", "gitlab"],
    "linux": ["linux", "ubuntu"],
    "rest api": ["rest api", "restful", "rest"],
    "graphql": ["graphql"],
    "websocket": ["websocket", "websockets", "socket.io"],
    "webrtc": ["webrtc"],
    "livekit": ["livekit"],
    "machine learning": ["machine learning", "ml"],
    "deep learning": ["deep learning"],
    "nlp": ["nlp", "natural language processing"],
    "llm": ["llm", "large language model", "large language models"],
    "pytorch": ["pytorch", "torch"],
    "tensorflow": ["tensorflow", "tfjs", "tensorflow.js"],
    "scikit-learn": ["scikit-learn", "sklearn"],
    "pandas": ["pandas"],
    "numpy": ["numpy"],
    "opencv": ["opencv", "cv2"],
    "fastapi": ["fastapi"],
    "flask": ["flask"],
    "django": ["django"],
    "prisma": ["prisma"],
    "typeorm": ["typeorm"],
    "jwt": ["jwt", "json web token"],
    "oauth": ["oauth", "oauth2", "google auth", "github auth"],
    "microservices": ["microservices", "microservice"],
    "system design": ["system design"],
    "data structures": ["data structures", "dsa"],
    "algorithms": ["algorithms"],
    "vlsi": ["vlsi"],
    "verilog": ["verilog"],
    "embedded": ["embedded", "embedded systems"],
    "iot": ["iot", "internet of things"],
}


CORE_SECTIONS = [
    "summary",
    "skills",
    "experience",
    "projects",
    "education",
    "certifications",
]


INDUSTRY_TAGS = {
    "web development": ["react", "next.js", "node.js", "express", "html", "css"],
    "backend": ["nestjs", "node.js", "postgresql", "mongodb", "redis", "docker"],
    "ai/ml": ["machine learning", "deep learning", "nlp", "pytorch", "tensorflow", "scikit-learn"],
    "cloud/devops": ["docker", "kubernetes", "aws", "azure", "gcp", "linux"],
    "realtime systems": ["websocket", "webrtc", "livekit", "redis"],
    "electronics/vlsi": ["vlsi", "verilog", "embedded", "iot"],
}
